# 16.3 發生錯誤時使用 defer 關閉一個檔案

如果你在一個 `for` 迴圈內部處理一系列檔案，你需要使用 `defer` 確保檔案在處理完畢後被關閉，例如：

```go
for _, file := range files {
    if f, err = os.Open(file); err != nil {
        return
    }
    // 這是錯誤的方式，當迴圈結束時文件沒有關閉
    defer f.Close()
    // 對檔案進行操作
    f.Process(data)
}
```

但是在迴圈內結尾處的 `defer` 沒有執行，所以檔案一直沒有關閉！垃圾回收機制可能會自動關閉檔案，但是這會產生一個錯誤，更好的做法是：

```go
for _, file := range files {
    if f, err = os.Open(file); err != nil {
        return
    }
    // 對檔案進行操作
    f.Process(data)
    // 關閉檔案
    f.Close()
 }
```

**`defer` 僅在函式回傳時才會執行，在迴圈內的結尾或其他一些有限範圍的程式碼內不會執行。**

## 連結

- [目錄](directory.md)
- 上一節：[誤用字串](16.2.md)
- 下一節：[何時使用 new() 和 make()](16.4.md)
